@startuml C4Context_ToBe
!include C4_Context.puml

Person(user_new, "Новый клиент банка", "Посетитель сайта, который пока не приходил в отделение, и не имеет доступа в интернет-банк")
Person(user, "Клиент банка", "Ранее уже подтвержден в системах банка")

System_Boundary(site, "Сайт") {
    System(deposites_site, "Депозиты", "Актуальные предложения по депозитам, расссчитанные по общим ставкам")
}

System_Boundary(lk, "Интернет-банк") {
    System(lk_deposites, "Управление депозитами", "Просмотр предложений по персональным ставкам, оформление заявок на депозит")
}

System_Boundary(deposites, "Управление депозитами") {
    System(abs_deposites, "Управление депозитами", "Управление заявками на открытие депозитов")
   Person(deposites_user, "Сотрудник отдела депозитов", "Обрабатывает заявки на открытие депозитов")
}

'System_Boundary(credits, "Управление заявками на кредиты клиентов") {'
 '   System(abs_credits, "Управление заявками на кредиты клиентов", "Первичный 'ввод заявок, перечисление сред по одобренным кредитам")
'    Person(credits_user, "Сотрудник отдела кредитования", "Обрабатывает заявки 'на открытие кредитов")
'}

System_Boundary(call, "Call-центр банка") {
    System(call_system, "Система call-центра банка", "Регистрирует задачи на звонки")
    Person(call_user, "Сотрудник call-центра", "Выполняет звонки клиентам")
}

System_Boundary(sms_systems, "СМС нотификации") {
System(sms, "СМС-шлюз")
}

System_Ext(telecom, "Телеком-профайдер", "Обработка запросов на СМС-нотификации")

Rel(sms, telecom, "Отправка СМС")
Rel(telecom, user_new, "СМС-нотификации")
Rel(telecom, user, "СМС-подтверждения")

Rel(user_new, deposites_site, "Просматривает предложения по открытию депозитов, оставляет заявку")
Rel(deposites_site, call_system, "Регистрирует заяки на звонок клиенту")
Rel(call_system, call_user, "Задачи на звонок клиенту")
Rel(call_user, user_new, "Уточняет детали заявки на депозит")
Rel(call_system, abs_deposites, "Регистрирует заявки на депозиты")


Rel(user, lk_deposites, "Просматривает предодобренные предложения по открытию депозитов, оставляет заявку")
Rel(lk_deposites, sms, "Запрашивает подтверждение заявки на депозит")
Rel(lk_deposites, abs_deposites, "Регистрирует заявки на депозит")
Rel(abs_deposites, sms, "Уведомление о предодобрении заявки на депозит")

Rel_Back(deposites_user, abs_deposites, "Обрабатывает заявки")
'Rel(abs_deposites, abs_credits, "Заявка на спецальную ставку по депозиту")
'Rel(abs_credits, credits_user, "Подтверждение спецальной ставки по депозиту")

@enduml